import { KUBIT_STATES } from 'constants';

const badIntentionList = [
  'lazarento',
  'arrombado',
  'foda',
  'foda-se',
  'vai se foder',
  'vai a merda',
  'arrombada',
  'fudeo',
  'fudeu',
  'gozar',
  'gozada',
  'merda',
  'bosta',
  'punheta',
  'filho da puta',
  'filha da puta',
  'punhetinha',
  'punheteiro',
  'fdp',
  'cuzão',
  'cusão',
  'cusão',
  'viado',
  'veado',
  'feio',
  'viadinho',
  'xota',
  'putaria',
  'putero',
  'puto',
  'puteiro',
  'bilau',
  'vadiazinha',
  'putinha',
  'babaca',
  'retardado',
  'cusinho',
  'cuzinho',
  'filho de um corno',
  'rapariga',
  'rabão',
  'vadia',
  'puta',
  'arrombada',
  'caralho',
  'broxa',
  'imbecil',
  'imbessil',
  'bastarda',
  'bastardo',
  'buceta',
  'bucetuda',
  'vsf',
  'vai se foder',
  'boceta',
  'cu',
  'rola',
  'rolas',
  'biscate',
  'pau no cu',
  'pau no seu cu',
  'pica',
  'pika',
  'piroca',
  'piroka',
  'coco',
  'cocozão',
  'pirok',
  'caraio',
  'vai tomar no cu',
  'vagabunda',
  'vagaba',
  'porra',
  'corno',
  'bixa',
  'bicha',
  'baitola',
  'boquete',
  'bronha',
  'brioco',
  'caga',
  'enrabada',
  'enrabado',
  'cagar',
  'cagado',
  'cagada',
  'arregaçada',
  'arregaçado',
  'bixinha',
  'bichinha',
  'bichona',
  'bixona',
  'arregassado',
  'arregassada',
  'chota',
  'chupada',
  'chupeta',
  'xupeta',
  'grelo',
  'grelinho',
  'greluda',
  'otario',
  'otaria',
  'prega',
  'rabuda',
  'raxada',
  'siririca',
  'tesuda',
  'tezuda',
  'xavasca',
  'chavasca',
  'xibiu',
  'xoxota',
  'chochota',
  '*',
];

const goodIntentionList = [
  'eu te amo',
  'amor',
  'amigo',
  'lindo',
  'bonito',
  'parceiro',
  'legal',
  'divertido',
  'able',
  'aceita',
  'aceitação',
  'aceitável',
  'aceito',
  'aceitando',
  'ação',
  'ativar',
  'active',
  'add',
  'adição',
  'adorável',
  'vantagem',
  'afirme',
  'sem idade',
  'concorda',
  'agradável',
  'aid',
  'aim',
  'abundância',
  'prestação de contas',
  'realização',
  'realizar',
  'exactidão',
  'façanha',
  'alcançar',
  'agradecimento',
  'adaptabilidade',
  'adventure',
  'adventurous',
  'agilidade',
  'agilidade',
  'ambição',
  'antecipação',
  'agradecemos',
  'appreciation',
  'grata',
  'appreciativeness',
  'assertividade',
  'assertiva',
  'atenção',
  'audácia',
  'aware',
  'consciência',
  'autêntico',
  'autenticidade',
  'abracadabra',
  'atração',
  'permitem',
  'permitindo',
  'carinho',
  'carinhoso',
  'absorvido',
  'alert',
  'surpreendido',
  'awe',
  'awed',
  'animate',
  'animado',
  'animando',
  'animação',
  'animateness',
  'ardente',
  'surpresa',
  'impressionante',
  'awesomeness',
  'excitado',
  'surpreendido',
  'astonishing',
  'divertido',
  'air',
  'airness',
  'aloha',
  'adore',
  'admire',
  'admirável',
  'allure',
  'angel',
  'angélico',
  'o altruísmo',
  'altruístas',
  'abundam',
  'abundante',
  'abounds- abundante',
  'absoluto',
  'absolutamente',
  'acessível',
  'aclamado',
  'acomodar',
  'acomodado',
  'acomodação',
  'acomodando',
  'ampla',
  'apreciativo alegria',
  'amin',
  'accentuactivity',
  'actability',
  'afável',
  'vivacidade ',
  'altrucause',
  'amável',
  'surpresa',
  'atrativo',
  'alive',
  'vivacidade',
  'acclaim',
  'satisfação abundante',
  'aclamação',
  'realizado',
  'realizações',
  'preciso',
  'precisamente',
  'achievable',
  'realizações',
  'ação para a felicidade',
  'passos activa e construtiva',
  'atos de bondade',
  'adaptável',
  'adaptáveis',
  'adequada ',
  'admiravelmente',
  'admiração',
  'admirado',
  'adorado',
  'adorando',
  'adoração',
  'advanced',
  'vantajosa',
  'vantajosamente',
  'vantagens',
  'afabilidade',
  'afavelmente',
  'a afinidade',
  'afirmação',
  'afirmativo',
  'afluência',
  'affluent',
  'pagar',
  'acessível',
  'acessível',
  'ágil',
  'ágil',
  'afabilidade',
  'agradavelmente',
  'alinhados tudo vai bem',
  'sedutor',
  'sedutora',
  'cura alternativa',
  'altruisticamente',
  'surpreenda',
  'surpresa',
  'espanta',
  'surpreendentemente',
  'amabilidade',
  'cordialidade',
  'amigável',
  'de forma amigável',
  'divertido',
  'recurso',
  'atraente',
  'aplaudir',
  'apreciáveis ​​apreciado',
  'aprecia',
  'apreciação da beleza',
  'com apreço',
  'for caso disso',
  'aprovação',
  'aprovar',
  'ardor',
  'arte de agradecimento',
  'art de quietude',
  'arte de bem-estar',
  'seguros',
  'por uma razão de ser',
  'acaronar',
  'acomodatícia',
  'altitudinarian',
  'palavras incrível',
  'amiabilybeatificar',
  'beatitude',
  'benéfico',
  'benefício',
  'benevolente',
  'amada',
  'melhor',
  'melhor',
  'bless',
  'bênção',
  'abençoado',
  'bliss',
  'blissfulness',
  'feliz',
  'flor',
  'balance',
  'equilibrado',
  'beleza',
  'bonito',
  'lindamente',
  'pertence',
  'pertencentes',
  'ousadia',
  'coragem',
  'brilliance',
  'brilhante',
  'bliss on tap',
  'além fabuloso',
  'biophilia',
  'brilhante',
  'brilho',
  'balistic de desmonte',
  'ardência',
  'cegando',
  'breathtaking',
  'borbulhando',
  'rebentar',
  'blisscipline',
  'buyancy',
  'otimismo',
  'vivacidade',
  'flutuabilidade breeziness',
  'brio',
  'ser extraordinário',
  'be happy ',
  'embelezar',
  'estando em repouso',
  'benfeitor',
  'benefícios',
  'a benevolência',
  'estado benevolentemente',
  'benevolentemente alegre of mind',
  'o melhor de todos os mundos possíveis',
  'além de',
  'beleza em todas as coisas',
  'beingness',
  'crível',
  'irmãos de sanguecuidados',
  'importando-se',
  'calma',
  'crie',
  'criativo',
  'criatividade',
  'criatividade',
  'capaz',
  'capacidade',
  'competentemente',
  'comemorar',
  'celebração',
  'certos',
  'certeza',
  'caritativo',
  'caridade',
  'charme',
  'encanto',
  'charmer',
  'escolha',
  'clean',
  'limpeza',
  'conforto',
  'confortável',
  'consolação',
  'cuddle',
  'carinho',
  'sinceridade',
  'cuidado',
  'desafio',
  'mudança',
  'alegre',
  'alegria',
  'clarity',
  'colaboração',
  'o comprometimento',
  'comunicação',
  'comunidade',
  'compaixão',
  'compassivo',
  'competente',
  'competência',
  'competency',
  'concentração',
  'confiável',
  'confiança',
  'consciência',
  'consistência',
  'consistente',
  'conteúdo',
  'contentamento',
  'continuidade',
  'continuando',
  'contribuição',
  'convicção',
  'convincentes',
  'cooperação',
  'coragem',
  'cortesia',
  'cortês curioso',
  'curiosidade',
  'chakra',
  'legal',
  'claro dirigido',
  'centrado',
  'estagnação',
  'companheirismo',
  'atencioso',
  'consideração',
  'comunhão',
  'connect',
  'conectado',
  'conexão',
  'conexidade ',
  'conquistar',
  'bonito',
  'carisma',
  'carismática',
  'recolhida',
  'vontade alegre',
  'elogios',
  'congruência',
  'cordial',
  'crank (up)',
  'capital',
  'rolhagem',
  'claro',
  'carícia',
  'bom humor',
  'palavras de cortesia',
  'contente',
  'aconchego',
  'cutenessdireção',
  'delicado',
  'decente',
  'desejável',
  'delicioso',
  'delícia',
  'do',
  'dream',
  'sonhador',
  'dynamic',
  'ousadia',
  'determinação',
  'prazer',
  'encantado',
  'delicioso',
  'fiabilidade',
  'desejo',
  'determinação',
  'dedicação',
  'dignidade',
  'assiduidade',
  'disciplina',
  'descoberta',
  'discrição',
  'diversidade',
  'drive',
  'dever',
  'divino',
  'deslumbrado',
  'disney',
  'devotado',
  'dandy',
  'daimon',
  'afável',
  'destacamento',
  'dedicado',
  'dauwtrappen',
  'brilhe',
  'deliciosaempatia',
  'empatia',
  'enfático',
  'fácil',
  'facilmente',
  'mais fácil',
  'educar',
  'educação',
  'educado',
  'eficiente',
  'activo',
  'habilitado',
  'energética',
  'energize',
  'energia',
  'engage',
  'intervir',
  'envolvido',
  'enjoy',
  'prazer',
  'bastante',
  'ansioso',
  'ânsia',
  'eficácia',
  'eficiência',
  'elation',
  'elegance',
  'incentive',
  'incentivo',
  'incentivada',
  'endurance',
  'igualdade',
  'excelência',
  'excelente',
  'excite',
  'emoção',
  'animado',
  'experiência',
  'competência',
  'exploração',
  'expressividade',
  'expressando',
  'iluminação',
  'eterno',
  'exaltação',
  'emular',
  'empower',
  'responsabilizar',
  'autorizado',
  'expansivo',
  'emocionante',
  'entusiasmado',
  'entusiasmo',
  'redigido',
  'encantado',
  'em transe',
  'eufórico',
  'exaltado',
  'encantado',
  'exuberante',
  'exuberance',
  'expectante',
  'equânime',
  'animada',
  'eficácia',
  'facilidade',
  'exemplares',
  'extraordinário',
  'sério',
  'elevate',
  'elevado',
  'equanimidade',
  'a facilidade de mente',
  'animado antecipação',
  'extra',
  'equidade',
  'eqüitativa',
  'equitable',
  'fácil de falar',
  'de fácil abordagem',
  'ecstatify',
  'eudemonismo',
  'eudaemonist',
  'eudaemonistic',
  'eudaimonia',
  'eudamonia',
  'evolui',
  'exaltando',
  'exstatisfy',
  'exultante',
  'astronômico',
  'campeão ‘',
  'elétrico',
  'enormous ',
  'excepcional',
  'emocionante',
  'requintado',
  'sem esforço',
  'eunoia',
  'ecosofia',
  'efervescência',
  'abrace',
  'autorizando palavras',
  'palavras encorajadoras',
  'erlebnisfantastic',
  'se sentir bem',
  'sentir-se bem',
  'flow',
  'fluxo',
  'fabuloso',
  'fair',
  'fé',
  'fiel',
  'fame',
  'favorito',
  'justiça',
  'família',
  'fidelidade',
  'flexibilidade',
  'foco',
  'floreio',
  'perdoe',
  'perdoando',
  'perdão',
  'coragem',
  'free',
  'liberdade',
  'frugalidade',
  'fun',
  'futuro',
  'amigo',
  'amigo',
  'amizade',
  'uso',
  'fascinate',
  'fascinada',
  'cumprir',
  'cumpridas',
  'food',
  'resoluto',
  'feistiness',
  'viável',
  'fina',
  'sem medo',
  'festivo',
  'festiveness',
  'fit',
  'fantabulous',
  'freecycle',
  'funerific',
  'funology',
  'flawless',
  'famoso',
  'fantasia',
  'altivo',
  'ftw',
  'piadas engraçadas',
  'ostentando',
  'fondleglow',
  'generoso',
  'generosidade',
  'gerar',
  'genial',
  'genius',
  'genuíno',
  'presente',
  'dê',
  'dar',
  'bom',
  'a bondade',
  'indo para o extra mile',
  'grace',
  'gratidão',
  'gratefulness',
  'crescer',
  'crescimento',
  'guia',
  'orientadores',
  'orientação',
  'deus',
  'aterrada',
  'glory ',
  'a piedade',
  'bons sentimentos',
  'groovy',
  'vertiginoso',
  'glad',
  'boa saúde',
  'glamour',
  'rindo',
  'deusa',
  'lindo',
  'gorgeousness',
  'grandiosidade',
  'generavity',
  'cavalheiro',
  'gigantesco',
  'grande',
  'grande',
  'gengibre',
  'bem-humorada',
  'reputação',
  'greatful',
  'gemutlichkeit',
  'gibigiana',
  'gigil',
  'boa espírito residente',
  'boa palavra',
  'palavras boas',
  'bem-humorada',
  'reputaçãoesperança',
  'esperança',
  'felicidade',
  'feliz',
  'felizmente',
  'harmonioso',
  'harmonizar',
  'harmonia',
  'saúde',
  'saudável',
  'coração',
  'olá',
  'help',
  'útil',
  'ajudando',
  'hot',
  'honesto',
  'honestidade',
  'humano',
  'humor',
  'gentileza',
  'herói',
  'heroísmo',
  'santa',
  'santidade',
  'honra',
  'hospitalidade',
  'humilde',
  'céu',
  'celestial',
  'halo',
  'heartfelt',
  'reconfortante',
  'unidirecionalidade',
  'feliz hearted',
  'diligente',
  'bonito',
  'enorme',
  'high-spiritedness',
  'altamente distinto',
  'palavras feliz',
  'coração de abertura',
  'hospitaleiro',
  'prosperidade humana',
  'altamente distintaimaginação',
  'inspire',
  'inspiração',
  'inspirado',
  'inspirado',
  'em-amor',
  'idea',
  'incrível',
  'inovar',
  'inovação',
  'interessante',
  'juros',
  'interessado',
  'melhoria',
  'independência',
  'influência',
  'criatividade',
  'paz interior',
  'insight',
  'insightfulness',
  'perspicaz',
  'integridade',
  'inteligência',
  'inteligente ',
  'a intensidade',
  'a intimidade',
  'intuição',
  'criatividade',
  'investimento',
  'intenção',
  'revigorar',
  'revigorado',
  'intrigado',
  'envolver',
  'envolvidos',
  'inclusão',
  'inocente',
  'inefável',
  'intrepid',
  'idealismo',
  'iluminação',
  'iluminado',
  'incomparável',
  'invencível',
  'inquisitive',
  'infinito',
  'infinidade',
  'ilustre inner ',
  'ichariba chode',
  'ikigai',
  'cuteness incredible',
  'habitação',
  'palavras inspiradas',
  'inspiração palavra',
  'palavras inspiradoras',
  'iridescent',
  'ilustre inneralegria',
  'alegre',
  'alegria',
  'piada',
  'alegre',
  'jovial',
  'apenas',
  'justiça',
  'jubilante',
  'juvenescent',
  'jumpy',
  'jammin',
  'jubilingobondade',
  'espécie',
  'tipo-coração',
  'gentilmente',
  'mantenha-up',
  'beijo',
  'conhecimento',
  'gatinhos',
  'keen',
  'kaajhuab',
  'kalon',
  'kilig',
  'palavras amáveis',
  'koibito kibungosto',
  'para rir',
  'rir',
  'aprender',
  'learning',
  'vida',
  'vivo',
  'vida',
  'de luxo',
  'longevidade',
  'lealdade',
  'fiel',
  'love',
  'adorável',
  'amando',
  'liberdade',
  'logic',
  'leader',
  'liderança',
  'sorte',
  'lucky',
  'luz',
  'bondade amorosa',
  'alegre',
  'vida do partido',
  'bonito',
  'amando aceitação',
  'sentimentos amorosos',
  'trabalhadores da luz',
  'guiar',
  'luz de nevoeiro',
  'vidas através',
  'palavras do amor',
  'amante da beleza',
  'brilhante',
  'brilhante coressignificado',
  'significativa',
  'mais',
  'magnífico',
  'majestade',
  'muitos',
  'maravilhoso',
  'merit',
  'motive',
  'milagre',
  'mágica',
  'fazendo uma diferença',
  'mastery',
  'maturidade',
  'consciente',
  'mindfulness',
  'modéstia',
  'motivação',
  'motivational',
  'misericórdia',
  'meditação',
  'alucinante',
  'maduro',
  'movido',
  'movimento',
  'mutualidade',
  'luto',
  'meliorismo',
  'mench',
  'mindsight',
  'mindsight',
  'major',
  'suave',
  'palavras significativas',
  'memorável',
  'morphing',
  'palavras motivado',
  'palavras de motivação',
  'palavras inspiradores',
  'mudançasnobre',
  'alimentando',
  'consolide',
  'não-resistência',
  'não resistente',
  'novo',
  'agradável',
  'nirvana',
  'puro',
  'feito-natureza',
  'nutrir',
  'nutrido',
  'nutritivo',
  'alimentação',
  'namaste',
  'neotenia',
  'palavras bonitasoptimista',
  'otimista',
  'pendentes',
  'ok',
  'on',
  'em diante',
  'open',
  'abertamente',
  'abertura',
  'de mente aberta',
  'oportunidade',
  'original',
  'a abertura',
  'otimismo',
  'ordem',
  'organização',
  'originalidade',
  'resultado',
  'orientação',
  'obediente',
  'de coração aberto',
  'omg',
  'superado',
  'om mani padme',
  'extrovertido',
  'unidade',
  'outernationalist',
  'excessivamente otimista',
  'perfeito',
  'perfeição',
  'energia positiva',
  'pensamentos positivos',
  'eventos positivos',
  'circunstâncias positivas',
  'crenças positivas',
  'paz',
  'pacificar',
  'paradise',
  'paradisíacas',
  'paixão',
  'apaixonado',
  'por favor',
  'pure',
  'perspectivas',
  'perseverança',
  'persistência',
  'crescimento pessoal',
  'prazer',
  'positivo',
  'atitude positiva palavras',
  'o poder',
  'poderoso',
  'praticidade',
  'precisão',
  'prontidão',
  'presença',
  'preservação',
  'privacidade',
  'proatividade',
  'proactive',
  'progresso',
  'prosperidade próspero',
  'pontualidade',
  'pontual',
  'paciência',
  'orgulhoso',
  'satisfeito',
  'play',
  'brincalhão',
  'ludicidade',
  'a participação',
  'a finalidade',
  'pick-me -up',
  'pronia',
  'pias',
  'filhotes de cachorro',
  'educado',
  'espírito positivo',
  'pensamento positivo',
  'bonito',
  'muito',
  'perdão',
  'perkiness',
  'picante',
  'posichoice',
  'posidriving',
  'posifit',
  'posilenz',
  'posimass',
  'posiminder',
  'posiratio',
  'posiripple',
  'posirippler',
  'posiripples',
  'posisinger',
  'posisite ',
  'posistrength',
  'positibilitarian',
  'positraction',
  'positude',
  'posivalues',
  'posiword',
  'possibilitado',
  'presteza',
  'proto',
  'impagável',
  'pep',
  'peppiness',
  'permalicious',
  'corajosa',
  'pollyannaism',
  'orgulho',
  'sentimentos positivos',
  'paz de espírito',
  'palavras',
  'calmo',
  'petrichor',
  'philocalist',
  'emoções positivas',
  'sentimentos positivos vocabulário positivo',
  'palavras do poder',
  'palavras positivas poderosos',
  'palavras poderosas',
  'power-on',
  'power-up',
  'protegerqualidade',
  'calmo',
  'tranquilidade',
  'catita',
  'de repouso',
  'rainha',
  'acelerando',
  'quiddity',
  'repouso mente',
  'palavras de qualidaderespeito',
  'radiante',
  'pronto',
  'prontidão',
  'real',
  'a realidade',
  'razão',
  'recomendar',
  'refresh',
  'refrescado',
  'relax',
  'relaxado',
  'alívio',
  'aliviar',
  'aliviado',
  'notável',
  'a racionalidade',
  'o reconhecimento',
  'relações',
  'confiável',
  'confiabilidade',
  'religião',
  'desenvoltura',
  'responsabilidade',
  'retidão',
  'assunção de riscos',
  'romance',
  'revelação',
  'revived',
  'restaurar',
  'restaurado',
  'rest',
  'descansado',
  'renovar',
  'renovada',
  'rejuvenescer',
  'rejuvenescido',
  'êxtase',
  'arrebatador',
  'resilient',
  'resilience',
  'reverência',
  'ripe',
  'renascido',
  'parentesco',
  'rasasvada',
  'repose',
  'rosiness',
  'ceder',
  'de renome',
  'respeitada',
  'rainbow',
  'romântico',
  'ceder',
  'renomadoâmbito',
  'smile',
  'sorriso',
  'soulmate',
  'soul',
  'com alma',
  'sagrado',
  'safe',
  'segurança',
  'seguro',
  'seguro',
  'segurança',
  'sustentar',
  'sustentado',
  'save',
  'poupança',
  'simples',
  'simplificar',
  'abnegação',
  'auto-estima',
  'serviço',
  'simplicidade',
  'sinceridade',
  'habilidade',
  'hábil',
  'espírito',
  'sereno',
  'serenidade',
  'estabilidade',
  'resistência',
  'estilo',
  'sistematização',
  'o amor-próprio',
  'se esforçam',
  'a salvação',
  'a auto-estima',
  'auto-perdão',
  'a serve',
  'simpático',
  'autocompaixão',
  'auto-bondade',
  'spellbound',
  'estimulado',
  'estimular',
  'estímulo',
  'satisfeito',
  'ainda',
  'surpreendido',
  'sleep',
  'expressão sexual',
  'abrigo',
  'auto-expressão',
  'espaço',
  'espaçosos',
  'a espontaneidade',
  'espontânea',
  'luz do sol',
  'spark',
  'faísca',
  'sparkles',
  'sweet',
  'doçura',
  'apoio',
  'apoio',
  'suportado',
  'sexy',
  'sexiness',
  'supreme suculenta',
  'querido',
  'estudo',
  'estudioso',
  'savour',
  'saboreando',
  'suficiente',
  'estupendo',
  'ganhos',
  'swaggy',
  'splendid',
  'a smart',
  'espetacular',
  'especial',
  'serendipity',
  'sinergia',
  'shine',
  'shining',
  'iniciar',
  'firmeza',
  'sublime',
  'sunniness',
  'superpotência',
  'corajosa',
  'shape -shifting virtuoso,-stretching alma',
  'palavras fortestrue',
  'trust',
  'confiante',
  'tato',
  'teach',
  'dócil',
  'equipe',
  'grato',
  'obrigado',
  'obrigado',
  'agradecimentos',
  'terapia',
  'tempo',
  'trabalho em equipe',
  'oportunidade',
  'tolerância',
  'tradição',
  'tranquilo',
  'tranquilidade',
  'verdade',
  'veracidade',
  'concurso',
  'emocionado',
  'touch',
  'tocado',
  'agradado',
  'à matéria',
  'de saber',
  'de ser conhecido',
  'para ser visto',
  'transformador',
  'transformação',
  'transformar',
  'triunfo',
  'thrive',
  'próspera',
  'tenacidade',
  'para ser',
  'transparente',
  'temul',
  'com ternura',
  'tidsoptimist',
  'tempo optimistaunificação',
  'unique',
  'melhoria',
  'ultimate',
  'incondicional',
  'upgrade',
  'útil',
  'de fácil utilização',
  'a unidade',
  'entende',
  'entendimento',
  'entendida',
  'unificação de mente',
  'up',
  'melhoria das qualificações',
  'inacreditável',
  'imperturbável',
  'irreal',
  'surpresa',
  'ousado',
  'prazer ousado',
  'insuportavelmente bonito ',
  'unhurry',
  'inacreditável',
  'imperturbável',
  'irreal',
  'espantovitalidade',
  'valor',
  'valores',
  'valioso',
  'virtuosa',
  'válido',
  'verificar a',
  'muito',
  'viável',
  'virtude',
  'vitória',
  'vitorioso',
  'variedade',
  'vulnerabilidade',
  'vulnerável',
  'vibrante',
  'voto',
  'vim',
  'vigor',
  'a veneração',
  'vocabuleverage',
  'versatilidadeworth',
  'digno',
  'dignidade',
  'riqueza',
  'warm',
  'o calor',
  'bem-vindo',
  'dispostos disposto',
  'vontade',
  'sabedoria',
  'sábio',
  'ganhou',
  'maravilhoso',
  'bem-estar',
  'sinceridade',
  'wow',
  'maravilha',
  'água',
  'poço',
  'bem estar',
  'bem estar',
  'inteiro',
  'maravi- trabalho',
  'win',
  'vencível',
  'vencer',
  'walwalunxo',
  'x-ray vision',
  'xenodochial',
  'xfactor',
  'xenophile',
  'hospitaleirosim',
  'a juventude',
  'jovem',
  'novo',
  'young-em-coração',
  'yippee',
  'yay',
  'ansiar',
  'sim',
  'sim',
  'gostoso',
  'iene',
  'yesability',
  'yugen',
  'yaraana',
  'yesable',
  'você é amado',
  'zeloso',
  'zelo',
  'zest',
  'picante',
  'zestful',
  'zippy',
  'zing',
  'zappy',
  'zany',
];

export const getIntention = (phrase) => {
  const hasBadIntention = badIntentionList.find((item) => phrase.includes(item));
  if (hasBadIntention) return KUBIT_STATES.TALKING_BAD;
  const hasGoodIntention = goodIntentionList.find((item) => phrase.includes(item));
  if (hasGoodIntention) return KUBIT_STATES.TALKING_GOOD;

  return KUBIT_STATES.TALKING;
};
